# Generated by Django 3.1.12 on 2025-01-22 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_listing_brand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='likedlisting',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
