# Generated by Django 5.1.6 on 2025-02-12 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20250122_1733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='likedlisting',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
